version: "3.8"

services:
  api:
    container_name: api-java
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  app:
    container_name: app-react
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
